In [82]:
from __future__ import absolute_import, division, print_function, unicode_literals

import tensorflow as tf

import os
import datetime
import tensorflow_hub as hub
import numpy as np
    
import pandas as pd
from sklearn.model_selection import train_test_split

In [161]:
df=pd.read_csv('email8.csv')

In [162]:
df = df[['TITLE','CATEGORY']]


In [ ]:
#'Business', 'Personal', 'Personmal_professional', 'logistic_arrangements', 'Employment_arrangement', 'Documen-editing']),
#        values=tf.constant([1, 2, 3, 4, 5, 6]),

In [163]:
df.columns

Index(['TITLE', 'CATEGORY'], dtype='object')

In [164]:
pd.set_option('display.max_colwidth', -1)
df

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Passing a negative integer is deprecated in version 1.0 and will not be supported in future version. Instead, use None to not limit the column width.
  """Entry point for launching an IPython kernel.


TITLE  \
0          stevenkeanenroncom rayalvarezenroncom subject iso ket stabil plan mimevers contenttyp textplain charsetusascii contenttransferencod bit xfrom steven j kean xto ray alvarez xcc xbcc xfolder stevenkeanenot foldersal document xorigin kean xfilenam skeannsf thank take lead note tim question handicap liklihood approv price move west base odd need better view anyon el ray alvarez pm jame steffesnaenronenron cc tim beldenhouectect joe hartsoecorpenronenron steven j keannaenronenron alan comnespdxectect steve waltonhouectect susan j anaenronenron subject iso ket stabil plan tim although there alway chanc impress ferc wont buy ban export would appear run afoul commerc claus certainli goe counter everyth ferc hope accomplish order initi le certain direct ferc go price sinc even staff recogn stumbl block recommend offer possibl variant iso submit revis tariff sheet approv yet unlik would tri implement plan near term tri without ferc approv possibl legal avenu might includ file complaint ferc ask fast track process fast measur week day andor seek inct relief court faster hard obtain imposs depend entir circumst keep post learn anyth new ray jame steff pm tim beldenhouectect cc joe hartsoecorpenronenron ray alvareznaenronenron steven j keannaenronenron alan comnespdxectect steve waltonhouectect susan j anaenron subject iso ket stabil plan ray plea take lead respond tim ferc v state action sue info whether iso would unilater jim joe hartsoecorpenronenron jame steffesnaenronenron ray alvareznaenronenron steven j keannaenronenron alan comnespdxectect steve waltonhouectect susan j anaenronenron cc subject iso ket stabil plan recent plan file ferc horribl two aggregi part cost base stand bid ban export know comment propos also look intelleg whether iso propos chanc get approv ferc approv ferc californian california ignor ferc attempt unilater implement chang likelihood fed step interven hear anyth matter plea keep post propos plan huge impact california ket need much advanc notic possibl                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        

In [166]:
X_train, X_test = train_test_split(df, test_size=0.2, random_state=111)

In [167]:
from sklearn.utils import class_weight

In [168]:
class_weights = list( class_weight.compute_class_weight(class_weight = 'balanced',classes = np.unique(df['CATEGORY']), y = df['CATEGORY']) )
                                             

In [169]:
df['CATEGORY'].value_counts()

Business                  834
logistic_arrangements     476
Document_editing          143
Personmal_professional    100
Employment_arrangement    74 
Personal                  36 
Name: CATEGORY, dtype: int64

In [170]:
class_weights.sort()

In [171]:
class_weights

[0.33233413269384493,
 0.5822829131652661,
 1.9382284382284383,
 2.7716666666666665,
 3.7454954954954953,
 7.699074074074074]

In [172]:
weights={}

In [173]:
for index, weight in enumerate(class_weights) :
  weights[index]=weight

In [174]:
weights

{0: 0.33233413269384493,
 1: 0.5822829131652661,
 2: 1.9382284382284383,
 3: 2.7716666666666665,
 4: 3.7454954954954953,
 5: 7.699074074074074}

In [175]:
dataset_train = tf.data.Dataset.from_tensor_slices((X_train['TITLE'].values, X_train['CATEGORY'].values))
dataset_test = tf.data.Dataset.from_tensor_slices((X_test['TITLE'].values, X_test['CATEGORY'].values))

In [176]:
for text, target in dataset_train.take(5):
  print ('Complaint: {}, Target: {}'.format(text, target))

Complaint: b'     stevenkeanenroncom rosaleeflemingenroncom subject letter presid energi effici immedi review requ sted mimevers contenttyp textplain charsetusascii contenttransferencod bit xfrom steven j kean xto rosale fleme xcc xbcc xfolder stevenkeannot foldersal document xorigin kean xfilenam skeannsf lin rosale fleme pm steven j keannaenronenron cc subject letter presid energi effici immedi review requ sted someth want forward rosale flemingcorpenron pm nemtzowaseorg pm cc dhamaseorg subject letter presid energi effici immedi review requ sted allianc board associ  know presid clinton consid releas oil strateg petroleum reserv perhap earli next sever day regardless think releas oil reserv hope help u take advantag opportun encourag presid renew effort pursu energi effici nation best longterm respons rise oil import due immediaci is ask let u know sign later day temb noon eastern plea respond sign on give u precis companyorgan name repli email call dave hamilton thank consider supp

In [177]:
for text, target in dataset_test.take(5):
  print ('Complaint: {}, Target: {}'.format(text, target))

Complaint: b'     suzannenimocksmckinseycom skeanenroncom subject california power crisi updat mimevers contenttyp textplain charsetusascii contenttransferencod bit xfrom xto skeanenroncom xcc xbcc xfolder stevenkeanenot foldersdiscuss thread xorigin kean xfilenam skeannsf pull togeth weeklysometim often sumi intern purpos would find help distribut list hope well look forward touch base soon forward suzann nimockshounorthamericamckinsey memorandum pru sheppard bcc suzann nimock pru sheppard b venki venkateshwara  ch california power crisi updat develop week week highlight includ continu indic issu ket power possibl remedi like remain high profil issu california elsewher retroact prospect iron situat respect qf qf power contract effect releas ket higher price court order requir reliant continu sell power iso even paid full time manner anoth stage emerg roll blackout ket power continu indic issu ket power settl simpli week lengthi polit influenti front page stori new york time ferc passi

In [178]:
table = tf.lookup.StaticHashTable(
    initializer=tf.lookup.KeyValueTensorInitializer(
        keys=tf.constant(['Business', 'Personal', 'Personmal_professional', 'logistic_arrangements', 'Employment_arrangement', 'Documen-editing']),
        values=tf.constant([0, 1, 2, 3, 4, 5]),
    ),
    default_value=tf.constant(-1),
    name="target_encoding"
)

@tf.function
def target(x):
  return table.lookup(x)

In [179]:
def show_batch(dataset, size=5):
  for batch, label in dataset.take(size):
      print(batch.numpy())
      print(target(label).numpy())

In [180]:
show_batch(dataset_test,6)

b'     suzannenimocksmckinseycom skeanenroncom subject california power crisi updat mimevers contenttyp textplain charsetusascii contenttransferencod bit xfrom xto skeanenroncom xcc xbcc xfolder stevenkeanenot foldersdiscuss thread xorigin kean xfilenam skeannsf pull togeth weeklysometim often sumi intern purpos would find help distribut list hope well look forward touch base soon forward suzann nimockshounorthamericamckinsey memorandum pru sheppard bcc suzann nimock pru sheppard b venki venkateshwara  ch california power crisi updat develop week week highlight includ continu indic issu ket power possibl remedi like remain high profil issu california elsewher retroact prospect iron situat respect qf qf power contract effect releas ket higher price court order requir reliant continu sell power iso even paid full time manner anoth stage emerg roll blackout ket power continu indic issu ket power settl simpli week lengthi polit influenti front page stori new york time ferc passiv approach 

In [181]:
def fetch(text, labels):
  return text, tf.one_hot(target(labels),6)

In [182]:
train_data_f=dataset_train.map(fetch)
test_data_f=dataset_test.map(fetch)

In [183]:
next(iter(train_data_f))

(<tf.Tensor: shape=(), dtype=string, numpy=b'     stevenkeanenroncom rosaleeflemingenroncom subject letter presid energi effici immedi review requ sted mimevers contenttyp textplain charsetusascii contenttransferencod bit xfrom steven j kean xto rosale fleme xcc xbcc xfolder stevenkeannot foldersal document xorigin kean xfilenam skeannsf lin rosale fleme pm steven j keannaenronenron cc subject letter presid energi effici immedi review requ sted someth want forward rosale flemingcorpenron pm nemtzowaseorg pm cc dhamaseorg subject letter presid energi effici immedi review requ sted allianc board associ  know presid clinton consid releas oil strateg petroleum reserv perhap earli next sever day regardless think releas oil reserv hope help u take advantag opportun encourag presid renew effort pursu energi effici nation best longterm respons rise oil import due immediaci is ask let u know sign later day temb noon eastern plea respond sign on give u precis companyorgan name repli email call d

In [184]:
train_data, train_labels = next(iter(train_data_f.batch(5)))
train_data, train_labels

(<tf.Tensor: shape=(5,), dtype=string, numpy=
 array([b'     stevenkeanenroncom rosaleeflemingenroncom subject letter presid energi effici immedi review requ sted mimevers contenttyp textplain charsetusascii contenttransferencod bit xfrom steven j kean xto rosale fleme xcc xbcc xfolder stevenkeannot foldersal document xorigin kean xfilenam skeannsf lin rosale fleme pm steven j keannaenronenron cc subject letter presid energi effici immedi review requ sted someth want forward rosale flemingcorpenron pm nemtzowaseorg pm cc dhamaseorg subject letter presid energi effici immedi review requ sted allianc board associ  know presid clinton consid releas oil strateg petroleum reserv perhap earli next sever day regardless think releas oil reserv hope help u take advantag opportun encourag presid renew effort pursu energi effici nation best longterm respons rise oil import due immediaci is ask let u know sign later day temb noon eastern plea respond sign on give u precis companyorgan name repli e

In [185]:
embedding = "https://tfhub.dev/google/tf2-preview/nnlm-en-dim128/1"
hub_layer = hub.KerasLayer(embedding, output_shape=[128], input_shape=[], 
                           dtype=tf.string, trainable=True)
hub_layer(train_data[:1])

<tf.Tensor: shape=(1, 128), dtype=float32, numpy=
array([[-5.36668479e-01,  2.96648532e-01, -2.35960677e-01,
        -7.86133170e-01,  7.59224454e-03,  2.68745120e-04,
        -5.61449938e-02,  1.00430414e-01,  1.67294934e-01,
         4.12043571e-01, -3.46034877e-02,  6.98514516e-03,
         6.34792924e-01,  6.97903847e-03,  5.81255443e-02,
        -1.02564089e-01,  2.65104741e-01,  1.81269526e-01,
        -3.67247522e-01, -1.71331704e-01,  1.82272434e-01,
        -3.31319094e-01,  1.00789450e-01,  8.74788165e-02,
        -2.69784275e-02, -3.32663864e-01,  1.96196258e-01,
         1.68560624e-01, -8.23349535e-01,  2.19287407e-02,
         3.83537143e-01, -1.22412682e-01, -5.27426377e-02,
         1.66614875e-01,  7.33617395e-02,  3.96031551e-02,
         6.77204924e-03,  1.49023980e-01,  1.81931719e-01,
         1.41072884e-01, -2.81311244e-01, -2.49071836e-01,
        -2.40921453e-02, -4.07013930e-02,  2.20076859e-01,
        -1.23953447e-01, -2.54662484e-01,  2.27577835e-01,
      

In [186]:
model = tf.keras.Sequential()
model.add(hub_layer)
for units in [128, 128, 64 , 32]:
  model.add(tf.keras.layers.Dense(units, activation='relu'))
  model.add(tf.keras.layers.Dropout(0.3))
model.add(tf.keras.layers.Dense(6, activation='softmax'))

model.summary()

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 keras_layer_4 (KerasLayer)  (None, 128)               124642688 
                                                                 
 dense_30 (Dense)            (None, 128)               16512     
                                                                 
 dropout_24 (Dropout)        (None, 128)               0         
                                                                 
 dense_31 (Dense)            (None, 128)               16512     
                                                                 
 dropout_25 (Dropout)        (None, 128)               0         
                                                                 
 dense_32 (Dense)            (None, 64)                8256      
                                                                 
 dropout_26 (Dropout)        (None, 64)               

In [187]:
model.compile(optimizer='adam',
              loss=tf.keras.losses.CategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

In [188]:
train_data_f=train_data_f.shuffle(70000).batch(64)
test_data_f=test_data_f.batch(64)

In [189]:
history = model.fit(train_data_f,
                    epochs=12,
                    validation_data=test_data_f,
                    verbose=1,
                    class_weight=weights)

Epoch 1/12


/usr/local/lib/python3.7/dist-packages/tensorflow/python/util/dispatch.py:1082: UserWarning: "`categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a sigmoid or softmax activation and thus does not represent logits. Was this intended?"
  return dispatch_target(*args, **kwargs)


21/21 [==============================] - 19s 828ms/step - loss: 1.8056 - accuracy: 0.2820 - val_loss: 1.2556 - val_accuracy: 0.3393
Epoch 2/12
21/21 [==============================] - 16s 770ms/step - loss: 1.4386 - accuracy: 0.3782 - val_loss: 1.2654 - val_accuracy: 0.4084
Epoch 3/12
21/21 [==============================] - 16s 781ms/step - loss: 1.2258 - accuracy: 0.3940 - val_loss: 1.1598 - val_accuracy: 0.5015
Epoch 4/12
21/21 [==============================] - 16s 740ms/step - loss: 1.0358 - accuracy: 0.5173 - val_loss: 1.0699 - val_accuracy: 0.6547
Epoch 5/12
21/21 [==============================] - 15s 736ms/step - loss: 0.9080 - accuracy: 0.6308 - val_loss: 1.1545 - val_accuracy: 0.6757
Epoch 6/12
21/21 [==============================] - 16s 750ms/step - loss: 0.7951 - accuracy: 0.7015 - val_loss: 0.9714 - val_accuracy: 0.7027
Epoch 7/12
21/21 [==============================] - 16s 747ms/step - loss: 0.7034 - accuracy: 0.7368 - val_loss: 1.1247 - val_accuracy: 0.7177
Epoch 8/12

In [190]:
len(list(dataset_test))

333

In [191]:
results = model.evaluate(dataset_test.map(fetch).batch(1663), verbose=2)

print(results)

1/1 - 0s - loss: 1.5488 - accuracy: 0.6937 - 160ms/epoch - 160ms/step
[1.5487793684005737, 0.6936936974525452]


In [192]:
test_data, test_labels = next(iter(dataset_test.map(fetch).batch(333)))

In [193]:
y_pred=model.predict(test_data)

11/11 [==============================] - 1s 91ms/step


In [194]:
from sklearn.metrics import classification_report

In [195]:
print(classification_report(test_labels.numpy().argmax(axis=1), y_pred.argmax(axis=1)))

              precision    recall  f1-score   support

           0       0.83      0.76      0.79       195
           1       0.00      0.00      0.00         4
           2       0.14      0.20      0.17        15
           3       0.60      0.77      0.68       100
           4       0.50      0.16      0.24        19

    accuracy                           0.69       333
   macro avg       0.42      0.38      0.38       333
weighted avg       0.70      0.69      0.69       333



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [196]:
from sklearn.metrics import confusion_matrix
confusion_matrix(test_labels.numpy().argmax(axis=1), y_pred.argmax(axis=1))

array([[148,   0,  12,  35,   0],
       [  0,   0,   0,   4,   0],
       [  7,   0,   3,   4,   1],
       [ 18,   0,   3,  77,   2],
       [  5,   0,   3,   8,   3]])

In [1]:
n=10
result=1
while n>0:
    
    result=n*result

    n=n-1
    
print(result)    

3628800


In [2]:
def cal_fectorial(num):
    n=num
    result=1
    while n>0:

        result=n*result

        n=n-1
    return result    

In [6]:
cal_fectorial(0)

1